### PR TITLE
Do not notify on skipped jobs

### PR DESCRIPTION
**Pull request by njibhu**
This change makes sure that the notify function will only report failed or cancelled jobs, and not skipped jobs.

### CODE REVIEW

**Review by jleeothon — APPROVED** [review]
:+1:

**Comment by jleeothon** [comment]
An example "bad" CI is here: https://github.com/wunderflats/api/actions/runs/2688526095

**Review by avlan — APPROVED** [review]

**Comment by sergei-kovalenko-wf** [comment]
I get notifications about this PR on my private email, which was used once 6 months ago and now should have been deleted from wundeflats github

**Comment by jleeothon** [comment]
> I get notifications about this PR on my private email, which was used once 6 months ago and now should have been deleted from wundeflats github

Maybe you have something enabled per repo? I had a similar problem when I just joined WF because I didn't use GH for work before, and I got subscribed to EVERYTHING automatically all the time.

**Comment by sergei-kovalenko-wf** [comment]
@jleeothon my account is set to watch automatically any repo I met, so as I started here, I was automatically subscribed to all public repositories. So I had now to go over them again and unsubscribe.

**Pull request merged**
