### PR TITLE
Create reusable GH action to upload to test dashboard

### PR DESCRIPTION
**Pull request by bartosz-maciaszek**
This PR introduces a new, reusable action to upload test results to the test dashboard. The action will be used in workflow files for our repos to avoid code duplication.

### CODE REVIEW

**Comment by jleeothon** [comment]
Afaik, you need to include `node_modules`

**Comment by despairblue** [comment]
> Afaik, you need to include `node_modules`

I see actions that have either that, or a `dist` folder were everything is compiled into.

You need to precompile it if you don't want to include the modules folder.

**Comment by bartosz-maciaszek** [comment]
@despairblue any preference for compiling over having `node_modules` (apart from the number of files in the PR)?

**Comment by bartosz-maciaszek** [comment]
Let's try with `ncc` :)

**Review by sergei-kovalenko-wf — APPROVED** [review]

**Pull request merged**
